/*
 * App URI: customizing/modifyCustomizing
 * Source Location: customizing/modifyCustomizing.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("customizing/modifyCustomizing", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			/************************************************
			 * modifyCustomizing.js
			 * Created at 2022. 6. 6. 오전 2:50:20.
			 *
			 * @author PSE
			 ************************************************/
			
			
			/*
			 * 루트 컨테이너에서 load 이벤트 발생 시 호출.
			 * 앱이 최초 구성된후 최초 랜더링 직후에 발생하는 이벤트 입니다.
			 */
			function onBodyLoad(/* cpr.events.CEvent */ e){
				
				var product_id = app.getHost().initValue.product_id;
				var product_name = app.getHost().initValue.product_name;
				
				app.lookup("product_id").setValue("product_id", product_id);
				app.lookup("getCustomizingList").send();
				console.log("getCustomizingList 서브미션 실행");
				
			}
			
			
			/*
			 * getCustomizingList 서브미션에서 submit-done 이벤트 발생 시 호출.
			 * 응답처리가 모두 종료되면 발생합니다.
			 */
			function onGetCustomizingListSubmitDone(/* cpr.events.CSubmissionEvent */ e){
				/** 
				 * @type cpr.protocols.Submission
				 */
				var getCustomizingList = e.control;
				
				app.lookup("productName").redraw();	
				app.lookup("grid_customizing").redraw();
				
			}
			
			
			/*
			 * "+" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onButtonClick(/* cpr.events.CMouseEvent */ e){
				/** 
				 * @type cpr.controls.Button
				 */
				var button = e.control;
				var grid_customizing = app.lookup("grid_customizing");
				grid_customizing.row
				var insertRow = grid_customizing.insertRowData(grid_customizing.getRowCount(), true);
				// + 버튼 클릭시 그리드 행 추가
				
			}
			
			
			/*
			 * "-" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onButtonClick2(/* cpr.events.CMouseEvent */ e){
				/** 
				 * @type cpr.controls.Button
				 */
				var button = e.control;
				
				var product_customizingList = app.lookup("product_customizingList");
				var delete_customizing = app.lookup("delete_customizing");
				var grid_customizing = app.lookup("grid_customizing");
				grid_customizing.showDeletedRow = false;
				
				var girdEndRowIndex = grid_customizing.getViewingEndRowIndex();
				var product_customizingEndRowIndex = product_customizingList.getRowCount() - 1;
				
				var checkedRow = grid_customizing.getCheckRowIndices();
				// 체크한 열이 없을 경우
				if(checkedRow.length == 0 || checkedRow == null){
					// 새로 추가 한 열을 삭제할 경우
					if(girdEndRowIndex > product_customizingEndRowIndex) {
						grid_customizing.deleteRow(girdEndRowIndex);
						// 제일 마지막 행 삭제
					}else { // 기존 열을 삭제할 경우
						delete_customizing.addRowData(
							{
								"delete_customizing_id" : product_customizingList.getValue(girdEndRowIndex, "customizing_id")
							}
						)
						product_customizingList.deleteRow(girdEndRowIndex);
						grid_customizing.deleteRow(girdEndRowIndex);
					} // end else
						
				} // end if checkedRow
				else { // 체크한 열이 있을 경우
					var i
					for( i = 0; i < checkedRow.length; i++){
						delete_customizing.addRowData(
							{
								"delete_customizing_id" : product_customizingList.getValue(checkedRow[i], "customizing_id")
							}
						)
						grid_customizing.deleteRow(checkedRow[i]);
					} // end for
				}
				
			}
			
			
			/*
			 * "수정" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onButtonClick3(/* cpr.events.CMouseEvent */ e){
				/** 
				 * @type cpr.controls.Button
				 */
				var button = e.control;
				
				app.lookup("modifyCustomizing").send();
				console.log("modifyCustomizing 서브미션 실행");
				
				
			}
			
			
			/*
			 * modifyCustomizing 서브미션에서 submit-done 이벤트 발생 시 호출.
			 * 응답처리가 모두 종료되면 발생합니다.
			 */
			function onModifyCustomizingSubmitDone(/* cpr.events.CSubmissionEvent */ e){
				/** 
				 * @type cpr.protocols.Submission
				 */
				var modifyCustomizing = e.control;
				
				cpr.core.App.load("customizing/customizingManagement", function(loadedApp){
						if(loadedApp){
				    		app.getHost().app = loadedApp;
				  		}
					});
				
			};
			// End - User Script
			
			// Header
			var dataSet_1 = new cpr.data.DataSet("delete_customizing");
			dataSet_1.parseData({
				"columns": [{"name": "delete_customizing_id"}],
				"rows": []
			});
			app.register(dataSet_1);
			
			var dataSet_2 = new cpr.data.DataSet("product_customizingList");
			dataSet_2.parseData({
				"columns": [
					{"name": "customizing_id"},
					{"name": "customizing_version"},
					{"name": "customized_function"},
					{"name": "department"},
					{
						"name": "employees_number",
						"dataType": "number"
					},
					{"name": "employees_name"},
					{
						"name": "start_date",
						"dataType": "string"
					},
					{"name": "end_date"}
				],
				"rows": []
			});
			app.register(dataSet_2);
			var dataMap_1 = new cpr.data.DataMap("product");
			dataMap_1.parseData({
				"columns" : [
					{
						"name": "product_id",
						"dataType": "number"
					},
					{"name": "product_name"}
				]
			});
			app.register(dataMap_1);
			
			var dataMap_2 = new cpr.data.DataMap("result");
			dataMap_2.parseData({
				"columns" : [{
					"name": "resultCode",
					"dataType": "number"
				}]
			});
			app.register(dataMap_2);
			
			var dataMap_3 = new cpr.data.DataMap("product_id");
			dataMap_3.parseData({
				"columns" : [{
					"name": "product_id",
					"dataType": "number"
				}]
			});
			app.register(dataMap_3);
			var submission_1 = new cpr.protocols.Submission("modifyCustomizing");
			submission_1.method = "put";
			submission_1.action = "/productMangement/modifyCustomizing";
			submission_1.addRequestData(dataMap_3);
			submission_1.addRequestData(dataSet_2);
			submission_1.addRequestData(dataSet_1, cpr.protocols.PayloadType.modified);
			submission_1.addResponseData(dataMap_2, false);
			if(typeof onModifyCustomizingSubmitDone == "function") {
				submission_1.addEventListener("submit-done", onModifyCustomizingSubmitDone);
			}
			app.register(submission_1);
			
			var submission_2 = new cpr.protocols.Submission("getCustomizingList");
			submission_2.action = "/productMangement/getCustomizingList";
			submission_2.addRequestData(dataMap_3);
			submission_2.addResponseData(dataMap_1, false);
			submission_2.addResponseData(dataSet_2, false);
			if(typeof onGetCustomizingListSubmitDone == "function") {
				submission_2.addEventListener("submit-done", onGetCustomizingListSubmitDone);
			}
			app.register(submission_2);
			
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 840px) and (max-width: 1023px)", "new-screen");
			app.supportMedia("all and (min-width: 770px) and (max-width: 839px)", "new-screen2");
			app.supportMedia("all and (min-width: 500px) and (max-width: 769px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"top" : "0px",
				"height" : "100%",
				"left" : "0px"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container();
			// Layout
			var xYLayout_2 = new cpr.controls.layouts.XYLayout();
			group_1.setLayout(xYLayout_2);
			(function(container){
				var output_1 = new cpr.controls.Output();
				output_1.value = "커스터마이징 이력";
				output_1.style.css({
					"font-weight" : "bold",
					"vertical-align" : "middle",
					"font-size" : "14pt",
					"text-align" : "left"
				});
				container.addChild(output_1, {
					"top": "15px",
					"left": "20px",
					"width": "201px",
					"height": "41px"
				});
				var group_2 = new cpr.controls.Container();
				// Layout
				var formLayout_1 = new cpr.controls.layouts.FormLayout();
				formLayout_1.topMargin = "0px";
				formLayout_1.rightMargin = "0px";
				formLayout_1.bottomMargin = "0px";
				formLayout_1.leftMargin = "0px";
				formLayout_1.horizontalSpacing = "0px";
				formLayout_1.verticalSpacing = "0px";
				formLayout_1.setColumns(["100px", "180px"]);
				formLayout_1.setRows(["30px"]);
				group_2.setLayout(formLayout_1);
				(function(container){
					var output_2 = new cpr.controls.Output();
					output_2.value = "제품명";
					output_2.style.css({
						"border-right-style" : "solid",
						"border-top-width" : "1px",
						"border-bottom-color" : "#b4b4b4",
						"border-right-width" : "1px",
						"border-left-color" : "#b4b4b4",
						"border-right-color" : "#b4b4b4",
						"border-left-width" : "1px",
						"border-top-style" : "solid",
						"border-left-style" : "solid",
						"border-bottom-width" : "1px",
						"border-top-color" : "#b4b4b4",
						"border-bottom-style" : "solid",
						"text-align" : "center"
					});
					container.addChild(output_2, {
						"colIndex": 0,
						"rowIndex": 0
					});
					var output_3 = new cpr.controls.Output("productName");
					output_3.style.css({
						"border-right-style" : "solid",
						"border-top-width" : "1px",
						"border-bottom-color" : "#b4b4b4",
						"border-right-width" : "1px",
						"border-bottom-width" : "1px",
						"border-top-color" : "#b4b4b4",
						"border-bottom-style" : "solid",
						"border-right-color" : "#b4b4b4",
						"border-top-style" : "solid",
						"text-align" : "center"
					});
					output_3.bind("value").toDataMap(app.lookup("product"), "product_name");
					container.addChild(output_3, {
						"colIndex": 1,
						"rowIndex": 0
					});
				})(group_2);
				container.addChild(group_2, {
					"top": "65px",
					"left": "20px",
					"width": "284px",
					"height": "38px"
				});
				var button_1 = new cpr.controls.Button();
				button_1.value = "수정";
				button_1.style.css({
					"background-color" : "#DAF2DA",
					"border-right-style" : "none",
					"border-radius" : "10px",
					"border-left-style" : "none",
					"border-bottom-style" : "none",
					"background-image" : "none",
					"border-top-style" : "none"
				});
				if(typeof onButtonClick3 == "function") {
					button_1.addEventListener("click", onButtonClick3);
				}
				container.addChild(button_1, {
					"top": "660px",
					"left": "735px",
					"width": "80px",
					"height": "25px"
				});
				var button_2 = new cpr.controls.Button();
				button_2.value = "+";
				button_2.style.css({
					"background-color" : "#eaf0ea",
					"border-bottom-color" : "#c2c2c2",
					"border-left-color" : "#c2c2c2",
					"border-top-color" : "#c2c2c2",
					"border-right-color" : "#c2c2c2",
					"background-image" : "none"
				});
				if(typeof onButtonClick == "function") {
					button_2.addEventListener("click", onButtonClick);
				}
				container.addChild(button_2, {
					"top": "102px",
					"left": "740px",
					"width": "34px",
					"height": "25px"
				});
				var button_3 = new cpr.controls.Button();
				button_3.value = "-";
				button_3.style.css({
					"background-color" : "#eaf0ea",
					"border-bottom-color" : "#c2c2c2",
					"border-left-color" : "#c2c2c2",
					"border-top-color" : "#c2c2c2",
					"border-right-color" : "#c2c2c2",
					"background-image" : "none"
				});
				if(typeof onButtonClick2 == "function") {
					button_3.addEventListener("click", onButtonClick2);
				}
				container.addChild(button_3, {
					"top": "102px",
					"left": "774px",
					"width": "34px",
					"height": "25px"
				});
				var group_3 = new cpr.controls.Container();
				// Layout
				var verticalLayout_1 = new cpr.controls.layouts.VerticalLayout();
				group_3.setLayout(verticalLayout_1);
				(function(container){
					var grid_1 = new cpr.controls.Grid("grid_customizing");
					grid_1.init({
						"dataSet": app.lookup("product_customizingList"),
						"collapsible": true,
						"columns": [
							{"width": "25px"},
							{"width": "75px"},
							{"width": "124px"},
							{"width": "84px"},
							{"width": "103px"},
							{"width": "88px"},
							{"width": "88px"}
						],
						"header": {
							"rows": [
								{"height": "27px"},
								{"height": "27px"}
							],
							"cells": [
								{
									"constraint": {"rowIndex": 0, "colIndex": 0, "rowSpan": 2, "colSpan": 1},
									"configurator": function(cell){
										cell.filterable = false;
										cell.sortable = false;
										cell.columnType = "checkbox";
										cell.style.css({
											"background-color" : "#eaf0ea"
										});
									}
								},
								{
									"constraint": {"rowIndex": 0, "colIndex": 1, "rowSpan": 2, "colSpan": 1},
									"configurator": function(cell){
										cell.filterable = false;
										cell.sortable = false;
										cell.text = "커스터마이징 버전";
										cell.style.css({
											"background-color" : "#eaf0ea"
										});
										cell.control = (function(){
											var output_4 = new cpr.controls.Output();
											output_4.dateValueFormat = "YYYYMMDDHH";
											output_4.style.css({
												"text-align" : "center"
											});
											return output_4;
										})();
									}
								},
								{
									"constraint": {"rowIndex": 1, "colIndex": 2},
									"configurator": function(cell){
										cell.filterable = false;
										cell.sortable = false;
										cell.text = "부서명";
										cell.style.css({
											"background-color" : "#eaf0ea"
										});
									}
								},
								{
									"constraint": {"rowIndex": 1, "colIndex": 3},
									"configurator": function(cell){
										cell.filterable = false;
										cell.sortable = false;
										cell.text = "사원번호";
										cell.style.css({
											"background-color" : "#eaf0ea"
										});
									}
								},
								{
									"constraint": {"rowIndex": 1, "colIndex": 4},
									"configurator": function(cell){
										cell.filterable = false;
										cell.sortable = false;
										cell.text = "성명";
										cell.style.css({
											"background-color" : "#eaf0ea"
										});
									}
								},
								{
									"constraint": {"rowIndex": 1, "colIndex": 5},
									"configurator": function(cell){
										cell.filterable = false;
										cell.sortable = false;
										cell.text = "시작일";
										cell.style.css({
											"background-color" : "#eaf0ea"
										});
									}
								},
								{
									"constraint": {"rowIndex": 1, "colIndex": 6},
									"configurator": function(cell){
										cell.filterable = false;
										cell.sortable = false;
										cell.text = "종료일";
										cell.style.css({
											"background-color" : "#eaf0ea"
										});
									}
								},
								{
									"constraint": {"rowIndex": 0, "colIndex": 2, "rowSpan": 1, "colSpan": 5},
									"configurator": function(cell){
										cell.text = "기능별 담당 개발자";
										cell.style.css({
											"background-color" : "#eaf0ea"
										});
									}
								}
							]
						},
						"detail": {
							"rows": [
								{"height": "60px"},
								{"height": "30px"}
							],
							"cells": [
								{
									"constraint": {"rowIndex": 0, "colIndex": 0, "rowSpan": 2, "colSpan": 1},
									"configurator": function(cell){
										cell.columnType = "checkbox";
									}
								},
								{
									"constraint": {"rowIndex": 0, "colIndex": 1, "rowSpan": 2, "colSpan": 1},
									"configurator": function(cell){
										cell.columnName = "customizing_version";
										cell.control = (function(){
											var inputBox_1 = new cpr.controls.InputBox("ipb2");
											inputBox_1.bind("value").toDataColumn("customizing_version");
											return inputBox_1;
										})();
									}
								},
								{
									"constraint": {"rowIndex": 1, "colIndex": 2},
									"configurator": function(cell){
										cell.columnName = "department";
										cell.control = (function(){
											var inputBox_2 = new cpr.controls.InputBox("ipb4");
											inputBox_2.bind("value").toDataColumn("department");
											return inputBox_2;
										})();
									}
								},
								{
									"constraint": {"rowIndex": 1, "colIndex": 3},
									"configurator": function(cell){
										cell.columnName = "employees_number";
										cell.control = (function(){
											var maskEditor_1 = new cpr.controls.MaskEditor("mse1");
											maskEditor_1.mask = "000000000";
											maskEditor_1.bind("value").toDataColumn("employees_number");
											return maskEditor_1;
										})();
									}
								},
								{
									"constraint": {"rowIndex": 1, "colIndex": 4},
									"configurator": function(cell){
										cell.columnName = "employees_name";
										cell.control = (function(){
											var inputBox_3 = new cpr.controls.InputBox("ipb5");
											inputBox_3.bind("value").toDataColumn("employees_name");
											return inputBox_3;
										})();
									}
								},
								{
									"constraint": {"rowIndex": 1, "colIndex": 5},
									"configurator": function(cell){
										cell.columnName = "start_date";
										cell.control = (function(){
											var dateInput_1 = new cpr.controls.DateInput("dti1");
											dateInput_1.bind("value").toDataColumn("start_date");
											return dateInput_1;
										})();
									}
								},
								{
									"constraint": {"rowIndex": 1, "colIndex": 6},
									"configurator": function(cell){
										cell.columnName = "end_date";
										cell.control = (function(){
											var dateInput_2 = new cpr.controls.DateInput("dti2");
											dateInput_2.bind("value").toDataColumn("end_date");
											return dateInput_2;
										})();
									}
								},
								{
									"constraint": {"rowIndex": 0, "colIndex": 2, "rowSpan": 1, "colSpan": 5},
									"configurator": function(cell){
										cell.columnName = "customized_function";
										cell.control = (function(){
											var textArea_1 = new cpr.controls.TextArea("txa1");
											textArea_1.placeholder = "기능을 입력하세요.";
											textArea_1.bind("value").toDataColumn("customized_function");
											return textArea_1;
										})();
									}
								}
							]
						},
						"rowGroup": [{
							"groupCondition": "customizing_version",
							"gheader": {
								"rows": [{"height": "30px"}],
								"cells": [{
									"constraint": {"rowIndex": 0, "colIndex": 0, "rowSpan": 1, "colSpan": 7},
									"configurator": function(cell){
										cell.expr = "\"[버전]    \" + customizing_version";
									}
								}]
							}
						}]
					});
					container.addChild(grid_1, {
						"autoSize": "none",
						"width": "720px",
						"height": "510px"
					});
				})(group_3);
				container.addChild(group_3, {
					"top": "137px",
					"left": "20px",
					"width": "795px",
					"height": "513px"
				});
			})(group_1);
			container.addChild(group_1, {
				"top": "0px",
				"left": "0px",
				"width": "828px",
				"height": "700px"
			});
			if(typeof onBodyLoad == "function"){
				app.addEventListener("load", onBodyLoad);
			}
		}
	});
	app.title = "modifyCustomizing";
	cpr.core.Platform.INSTANCE.register(app);
})();
